stages:
    - build
    - deploy

build-back:
    stage: build
    only : 
        - master 
        - develop
    script :
        # Java를 sdkman 으로 설치한 경우 JAVA_HOME 설정을 위해서만 필요
        - cd $CI_PROJECT_DIR/WebBlog_V1
        - chmod +x gradlew
        - ./gradlew build -x test
        - cp build/libs/*.jar ~/app1.jar
    tags :
        # !! tag 값이 동일하게 설정된 Runner만 파이프라인을 동작시킴
        # 여러 서버에 배포할때 서버별 runner 태그로도 활용(dev, stg, prd)
        - lawli1

build-front:
    stage: build
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - frontend/node_modules
    only : 
        - master 
        - develop
    script :
        # Node.js를 nvm 으로 설치한 경우만 필요
        - source "/home/itinfo_ssafy/.nvm/nvm.sh"
        - cd $CI_PROJECT_DIR/frontend
        - npm install
        - yarn build
        - sudo rm -rf /home/itinfo_ssafy/webblog/frontend/dist
        - sudo cp -rf dist /home/itinfo_ssafy/webblog/frontend/
    tags :
        - lawli1

deploy-back:
    stage: deploy
    only : 
        - master 
        - develop
    script :
        - cd $HOME
        - sudo chmod 777 /home/itinfo_ssafy/restart_backend1.sh
        - sudo /home/itinfo_ssafy/restart_backend1.sh
    tags :
        - lawli1

deploy-front:
    stage: deploy
    only : 
        - master
        - develop
    script :
        - ls -al /home/itinfo_ssafy/webblog/frontend/dist
    tags :
        - lawli1
